import pmma

pmma.init()

display = pmma.Display()
display.create(1280, 720)

text = pmma.Text()

events = pmma.Events()

registry = pmma.Registry()

while registry.running:
    print(display.get_fps())
    display.clear(255, 0, 0)

    text.render(
"""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin finibus augue quis sapien interdum laoreet. Quisque rutrum tortor ut nibh iaculis, eu posuere justo dignissim. Vestibulum auctor pharetra est, a pellentesque magna interdum in. Vivamus semper augue est, vitae ultrices nulla lobortis id. Aliquam molestie rhoncus mollis. Aliquam semper et felis ac fermentum. Etiam hendrerit congue velit, nec tincidunt lorem malesuada sit amet. Quisque consequat id risus facilisis egestas. Sed nec tortor id ipsum congue mattis ac at enim. Ut in mauris ac dolor dignissim aliquam quis sit amet nulla. Donec sodales felis ut quam hendrerit, sit amet facilisis nisi euismod. Aliquam mattis tortor ante, in bibendum sapien euismod nec. Aenean fringilla at justo in maximus. Nulla consectetur volutpat quam quis placerat. Vivamus aliquet tincidunt nisl. Pellentesque quis erat iaculis, scelerisque felis ac, imperdiet mauris.

Proin porta ante eget velit luctus scelerisque. Sed turpis risus, maximus non blandit eu, volutpat a urna. Vivamus accumsan elit ut eros feugiat, sed lobortis orci maximus. Nulla quis auctor enim, vitae sodales tellus. Proin tincidunt fermentum felis sed rutrum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce laoreet laoreet nisl. Pellentesque mattis ultricies ante, vitae luctus eros mollis a.

Sed egestas sapien enim, non feugiat metus facilisis ac. Ut lobortis efficitur elit, sit amet malesuada dolor cursus at. Aenean dictum felis eget tortor sagittis dapibus. Phasellus elementum at est eget tincidunt. Nullam sem diam, iaculis eu mauris in, dignissim efficitur erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi eu velit a mi viverra facilisis eget eget sapien. Nulla gravida purus ac pellentesque tempor. Nam eleifend odio velit, eu maximus sapien interdum vitae. Donec sit amet massa vel arcu dignissim dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam volutpat, enim vitae pulvinar viverra, urna sem luctus dolor, a blandit quam massa ut urna. Nam consectetur semper augue, id blandit ipsum. Aliquam nisi lacus, sodales id luctus non, posuere a risus.

Sed mattis placerat purus, id sodales dui malesuada eget. Vestibulum rhoncus lacinia eros at vehicula. Proin commodo lorem in augue elementum, eget aliquam leo ultrices. Nullam vel placerat nibh. Aenean nec hendrerit neque. Praesent eget purus justo. Nullam auctor nunc a ultrices euismod. Nulla arcu purus, porttitor at varius ac, tincidunt ut neque. Donec tortor massa, congue in dui id, imperdiet fringilla leo. Morbi ut ultricies neque. Morbi luctus tellus ac ante laoreet dapibus. Fusce sit amet leo ornare, euismod dui sed, tempor nunc.

Nam ornare tellus ornare erat tempor vehicula. Vivamus posuere ullamcorper arcu. Nulla mattis varius interdum. Aenean at commodo lacus, rhoncus tempor nulla. Proin at dolor semper, convallis velit in, dictum purus. Vestibulum molestie neque elit, malesuada elementum tellus rutrum ut. Ut maximus aliquam nisi, non fringilla velit dignissim a.

Aliquam eu nunc rhoncus, viverra sem at, pulvinar tellus. Nullam in porta magna. Nulla congue a arcu vitae tempus. Fusce condimentum velit nec eros tempus commodo. Nulla feugiat lacus sapien, finibus tristique arcu pulvinar eget. Nam mattis nisi eget arcu gravida finibus. Donec malesuada ex ipsum, eget iaculis tellus luctus consectetur. Nullam massa leo, luctus a lectus sit amet, dignissim fringilla turpis. Nulla dui purus, facilisis sed risus in, convallis cursus eros. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce tristique, lacus eget egestas placerat, est ipsum ullamcorper elit, quis ullamcorper orci mauris at lectus. Cras porttitor quis diam ut semper. Ut sed accumsan justo. Nunc fringilla, augue in rhoncus eleifend, quam nisi volutpat leo, a viverra diam sapien ut sapien. Aenean rutrum fermentum odio finibus cursus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut leo id lectus dictum blandit. Phasellus consequat sem ut tortor pharetra sodales. Aenean vel arcu quis risus convallis eleifend vel et leo. Etiam sed tristique ante. Nullam a sapien ac felis tempus blandit eget quis justo. Praesent ut turpis vulputate, dapibus tellus in, vehicula nisl. Praesent volutpat lacus nec sem bibendum lobortis. Maecenas id erat aliquam lacus ultricies viverra. Quisque laoreet volutpat est in ullamcorper. Maecenas ornare est eu sem faucibus porta. Phasellus vitae lorem est. Suspendisse in neque nec quam fringilla tincidunt eu et diam. Fusce leo ex, luctus nec elit ultricies, semper bibendum sem.

Nulla rhoncus sapien ut elit venenatis, id auctor ligula pellentesque. Praesent id est id lorem vestibulum dictum. Nunc quis purus felis. Fusce nec porttitor tellus. Duis sodales iaculis tellus fringilla congue. Fusce commodo, mauris in pulvinar pharetra, elit orci imperdiet quam, ac egestas purus sem in arcu. Nullam in massa ut dolor elementum tincidunt eget eu sapien.

Vestibulum rutrum in diam at congue. Nunc faucibus ornare dui nec suscipit. Vivamus felis elit, maximus a lorem non, sollicitudin dictum massa. Duis ante sapien, pulvinar quis dui a, interdum rutrum diam. Duis sit amet scelerisque urna. Sed sodales nulla quis porttitor hendrerit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer in arcu sit amet diam consectetur sagittis auctor sit amet nunc. Suspendisse potenti.

Vivamus suscipit odio id magna fringilla, a consectetur augue aliquam. Maecenas dictum hendrerit placerat. Vivamus nec efficitur felis. Sed fermentum pellentesque tortor eu gravida. Nulla augue risus, vestibulum id malesuada elementum, eleifend a nisl. Morbi sem tellus, gravida in condimentum quis, venenatis at ligula. Vivamus neque est, mattis ut arcu eu, pharetra lacinia lacus.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi malesuada semper dignissim. Fusce ultrices enim vitae magna aliquam fringilla. Phasellus at felis dui. Suspendisse consectetur feugiat luctus. Sed hendrerit, lorem dapibus elementum finibus, risus augue eleifend tortor, pellentesque placerat elit ex ut quam. Cras vel velit dapibus, lobortis tellus quis, suscipit erat. Quisque tortor magna, finibus in rutrum id, aliquam sed enim.

Quisque vulputate eu ligula sit amet ullamcorper. Integer tincidunt, odio in suscipit ullamcorper, tortor risus elementum est, at pharetra magna ipsum a dolor. Pellentesque blandit enim magna, a viverra nunc dapibus sed. Curabitur pulvinar orci interdum diam pharetra, scelerisque auctor velit venenatis. Curabitur eget pretium augue. Morbi vestibulum sem id nisi ornare rutrum. Nunc volutpat leo eu est vulputate auctor. Donec aliquet libero porttitor ipsum imperdiet sodales. Nullam at metus vehicula, luctus erat in, ultricies urna. Quisque lobortis est vitae mi cursus maximus. Nullam malesuada turpis eu iaculis bibendum. Suspendisse potenti. Integer auctor lacus scelerisque lectus ultricies, id volutpat orci vulputate. Cras molestie mattis justo sit amet accumsan. Fusce eget augue urna. Praesent iaculis odio at velit tempus tempor.

Nunc sed quam sed purus malesuada pulvinar in vel lacus. Curabitur quis aliquet elit. Donec at erat non libero ullamcorper porttitor in blandit risus. Nam suscipit venenatis massa. Quisque porttitor feugiat lectus eget pretium. Nulla faucibus ac tortor at tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur lobortis cursus massa, at posuere dui efficitur et. Suspendisse accumsan, mauris a porttitor consequat, libero odio finibus erat, congue iaculis risus nisl et ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras interdum sit amet libero ut commodo.

Mauris consectetur eros a dui vulputate consectetur ultrices vitae eros. Vivamus pulvinar tristique nisi, eget venenatis purus ullamcorper vitae. Etiam varius fringilla convallis. Curabitur lobortis ex erat, non tincidunt mi auctor at. Mauris at arcu euismod, posuere turpis quis, luctus justo. Maecenas vel odio vitae lacus ornare ultricies. Pellentesque ipsum nibh, blandit ac semper sed, lacinia eu erat.

Maecenas vestibulum, elit quis posuere ultrices, odio mauris feugiat velit, vel finibus lorem massa id arcu. In hac habitasse platea dictumst. Vivamus a ultrices purus. Curabitur euismod erat nulla, et bibendum diam gravida nec. Maecenas a massa mauris. Pellentesque ligula ante, auctor quis consequat sed, consectetur at sem. In viverra purus placerat erat tincidunt, id dapibus ipsum pulvinar. Sed ut ullamcorper enim, at porta nulla. Nam accumsan maximus convallis. In elementum sollicitudin efficitur.

Nam molestie dignissim erat, in rutrum dolor dapibus eget. Fusce a viverra nunc. In rutrum nisl eu ultrices semper. Proin ut ex augue. Nulla accumsan lacus vitae enim fermentum placerat. Sed nec libero iaculis, elementum risus quis, tincidunt arcu. Donec scelerisque convallis lorem. Nullam eu eleifend ante, rhoncus vestibulum ipsum. Ut et ante eget metus venenatis vulputate mattis et magna. Fusce elementum nunc et nunc euismod commodo. Aliquam imperdiet nisl ut enim tempor, vitae lobortis metus pharetra. Fusce magna elit, blandit at nisi eu, lobortis aliquam ligula. Etiam molestie tortor sit amet laoreet cursus. Morbi vitae nunc a sem tincidunt ultricies et sit amet odio. Suspendisse est quam, cursus non risus ut, tincidunt faucibus eros. Sed eu dictum ex, a vestibulum nunc.

Nunc tristique mattis nunc, a pretium nisi fringilla ac. Suspendisse blandit purus sed elit convallis, id sagittis magna aliquam. Aliquam gravida, magna sit amet molestie commodo, augue quam fermentum lacus, et tincidunt ex est a nisi. Phasellus ut mauris eu velit auctor vestibulum. Vestibulum elementum elit nec lorem scelerisque, quis venenatis metus elementum. Sed dapibus massa a risus cursus, ut mattis turpis pretium. Suspendisse potenti. Nulla viverra, nibh nec feugiat tempor, turpis turpis tempus neque, quis scelerisque nulla dolor ut magna. Donec luctus erat eget turpis consequat, non sollicitudin odio commodo. In aliquam non nisl a fermentum. Praesent erat ligula, pretium vitae leo pharetra, imperdiet pretium ipsum. In quis ultricies enim. Sed tincidunt felis quam, sit amet mattis quam lacinia nec.

Proin a elit convallis, accumsan metus dictum, molestie nisi. Vivamus leo nisi, interdum in egestas et, porta at mi. Pellentesque tristique faucibus lectus, nec fringilla tellus fermentum et. Pellentesque ullamcorper, urna a fermentum mollis, leo risus aliquam quam, vel sollicitudin elit velit nec turpis. Nunc vel risus sollicitudin, egestas velit id, facilisis nisl. Pellentesque pellentesque velit pulvinar augue posuere feugiat. Praesent vel lacinia est, sit amet suscipit tortor.

Proin quam nisi, lacinia et erat vel, vestibulum accumsan orci. Suspendisse turpis neque, convallis non porta a, suscipit et felis. Cras cursus metus id purus porttitor porta. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec fermentum diam nec ligula pulvinar dictum. Ut metus enim, sodales nec sem sed, porta blandit sapien. Pellentesque tempus viverra mauris sit amet euismod. Sed eget orci laoreet, eleifend felis a, facilisis massa. Nunc vitae magna porttitor, elementum ante in, feugiat purus. Aliquam erat volutpat. Suspendisse vel neque semper, pellentesque sem sed, dictum metus. Cras lobortis velit quis pharetra efficitur.

Sed sit amet metus commodo, blandit ipsum ut, consectetur erat. Maecenas malesuada gravida convallis. Cras eget gravida neque. Nunc luctus ultricies congue. Pellentesque ultricies lectus iaculis finibus vestibulum. Aliquam ultricies, eros at aliquam auctor, leo lectus varius nunc, vel porttitor sapien lectus vel quam. Proin cursus mi nec magna ultrices, ut eleifend diam placerat. Nam volutpat lacinia lacus, id feugiat arcu tincidunt vitae.

In viverra, arcu mollis bibendum ullamcorper, urna arcu sollicitudin tortor, in imperdiet sem ipsum sit amet sem. Suspendisse elementum turpis neque, sit amet faucibus est ultrices at. Integer feugiat metus purus, vitae rutrum sapien tincidunt at. Fusce finibus volutpat nisi, vitae semper sapien finibus ut. Sed gravida risus eu elit aliquet cursus. Suspendisse potenti. Maecenas eget urna cursus, sollicitudin ligula mollis, ultrices quam.

Aenean sed quam venenatis, tincidunt nunc ac, lacinia velit. Donec posuere est lectus, ac vulputate est iaculis sed. Suspendisse id pulvinar lectus. Ut bibendum finibus erat, sed facilisis nisi suscipit vitae. Vestibulum faucibus ut libero quis ultrices. Fusce sagittis lacus volutpat, dictum orci eget, consectetur quam. Nulla tincidunt, neque at tincidunt aliquet, sapien metus scelerisque justo, ac vestibulum eros tortor nec enim. Maecenas imperdiet sem quis nisi fermentum, sed porta velit tempus. Phasellus pellentesque, ante ac pulvinar imperdiet, arcu neque rutrum nibh, id tempor turpis neque quis felis. Etiam rutrum interdum congue. Vivamus eget tincidunt tortor. Proin eleifend ligula at tempor dignissim.

Vestibulum commodo fermentum urna, nec scelerisque risus convallis vel. Etiam eleifend varius elit, in fermentum nisl sagittis ut. Morbi sit amet fermentum mauris. Sed sit amet arcu elit. Etiam mauris augue, volutpat id aliquet eget, porttitor id ante. Morbi viverra arcu sed lorem efficitur, non pulvinar orci consectetur. Nulla nec elit vitae sapien bibendum congue nec nec velit. Maecenas et ullamcorper leo. Nullam non purus quis orci ornare consequat. Suspendisse ac enim quis lectus congue imperdiet in ut dui. Nullam commodo sagittis diam. Mauris metus justo, interdum sed aliquet ac, suscipit id augue. Nulla gravida lectus ac lacus pellentesque, vel condimentum ipsum accumsan.

Maecenas sit amet hendrerit augue, eget pellentesque massa. Cras a justo ac turpis iaculis lacinia eu nec ipsum. Mauris justo quam, hendrerit consectetur pharetra quis, blandit sit amet nibh. Vivamus felis nunc, suscipit vel pretium eget, tempor id neque. Praesent congue dapibus sem quis lobortis. Pellentesque augue odio, iaculis at vehicula quis, blandit a leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras at ante egestas, aliquam lectus a, convallis enim. Sed a massa augue.

Maecenas in ligula magna. Phasellus vulputate tempus lorem quis interdum. Integer dui mi, auctor a dignissim quis, sodales sed nisi. Maecenas elit tellus, accumsan eget volutpat vel, dapibus sit amet dolor. Donec dui est, ultrices ut eros at, viverra ultricies ligula. Praesent elit justo, congue nec sapien id, porttitor sodales nunc. Morbi suscipit auctor convallis. Quisque quis viverra neque. Sed interdum interdum neque non suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas maximus et neque vitae euismod. Sed condimentum, ex et gravida gravida, felis dolor tristique metus, vitae varius odio turpis at orci. Cras scelerisque tristique risus, a venenatis mi.

Phasellus hendrerit nulla est, non maximus turpis vestibulum ut. Phasellus eros erat, blandit a vehicula sit amet, commodo in ex. Aliquam et convallis lectus. Cras non mattis nulla. Vestibulum pharetra molestie libero in vehicula. Praesent a posuere sem. Donec nibh purus, pellentesque non luctus sit amet, faucibus ac lectus. Suspendisse porta, elit pharetra iaculis egestas, risus leo sagittis mi, eu dictum augue tellus vitae lorem. Donec vulputate blandit ullamcorper. Maecenas suscipit laoreet malesuada. Nullam et tincidunt sapien, id molestie ante. Donec pulvinar neque vel sem efficitur, vehicula maximus risus blandit. Donec sollicitudin ultricies libero, at convallis sapien condimentum ac. Nulla facilisi. Integer vel fermentum ante.

Pellentesque ac neque in dui tristique fermentum. Aenean sed interdum leo. Vestibulum sit amet pellentesque velit, et malesuada tellus. Nullam vulputate molestie dolor sed consectetur. In ut dolor pulvinar, hendrerit leo at, viverra quam. Maecenas viverra laoreet nibh non semper. Suspendisse aliquam nec ex non malesuada. Integer placerat nulla sit amet convallis ultrices. Mauris sagittis lectus at velit convallis feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque iaculis ultrices velit sed vestibulum. Quisque imperdiet maximus risus, vitae tincidunt risus tempor sed. Sed a nunc lectus. Duis finibus ante in erat hendrerit elementum.

Curabitur at odio vel magna rhoncus lacinia id ac quam. Proin risus ligula, venenatis in odio mollis, lacinia dapibus libero. Maecenas a mattis nisi, nec rhoncus ligula. Nullam eleifend orci dolor, eu tristique lacus eleifend et. In iaculis mauris eu consectetur viverra. Nulla quis justo lorem. Cras quis ipsum id tellus viverra ornare. Morbi feugiat malesuada sagittis. Quisque ac ipsum quis enim rutrum hendrerit a nec magna. Sed mattis ultrices nibh. Pellentesque gravida nibh vel sollicitudin ultricies. Quisque sapien leo, interdum at commodo nec, tincidunt in neque. Suspendisse commodo posuere lacus a venenatis. Donec rhoncus mollis lectus auctor ultricies. Vivamus vitae ornare lorem.

Phasellus sollicitudin neque tellus, ut vestibulum lacus varius nec. Etiam at elit vitae massa porttitor faucibus posuere quis sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec sit amet velit sit amet tellus euismod fringilla. Fusce porta tortor elit, vel placerat ligula accumsan non. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc molestie mauris odio, in finibus enim hendrerit quis. Pellentesque rhoncus quis nunc in vestibulum. Nulla urna nisl, ullamcorper et condimentum vitae, porttitor id ligula. Nunc eget neque nec risus tempor efficitur. Maecenas vel justo mi. Maecenas vehicula quis nulla eu fermentum. Aenean urna ex, euismod pellentesque purus in, egestas mattis augue. Praesent vitae lobortis dolor, in facilisis nibh.

Mauris in lorem nisl. Suspendisse a elementum lectus. Pellentesque urna felis, vehicula sit amet fermentum quis, feugiat non magna. Aliquam maximus vel nisi eget viverra. Etiam placerat orci dignissim, dictum ante non, aliquet magna. Etiam dictum felis sem, at ultrices orci vestibulum at. Donec mattis ipsum nunc, eget molestie dui accumsan vel. Pellentesque id suscipit orci. Praesent malesuada augue et maximus auctor. Aliquam erat volutpat. Sed pretium neque a magna varius, et euismod elit placerat. Proin pharetra auctor tincidunt.

Morbi at semper libero, id facilisis felis. Duis arcu lectus, condimentum ac pellentesque id, porttitor imperdiet augue. Fusce ut ante erat. Vestibulum cursus quam ac diam sollicitudin, nec commodo ex pharetra. Donec vulputate tincidunt convallis. Nulla nisl nisi, varius id tortor eu, pulvinar posuere velit. Vivamus vitae libero a enim tincidunt venenatis. Donec turpis mauris, rutrum at dolor eu, cursus convallis libero. Proin aliquam lacinia purus, volutpat dignissim neque tristique vitae. Proin ut ultrices lorem. Aliquam lacinia ornare euismod. Nullam mauris magna, tincidunt ut tempus id, porttitor vitae augue. Morbi consectetur arcu non egestas cursus. Nunc auctor mattis nibh at rhoncus.

Pellentesque non ex quis diam gravida fermentum ac in est. Nulla vitae ligula quis urna condimentum dignissim. Morbi porttitor, mauris sollicitudin blandit rutrum, felis nunc dapibus dolor, eu porttitor tortor orci at leo. Nam varius eu massa a suscipit. Phasellus dignissim, mauris sit amet suscipit lacinia, quam purus ultrices metus, sed consequat felis justo non sem. Vivamus fringilla consectetur odio id volutpat. Donec sit amet viverra tortor, eu ullamcorper purus.

Aenean condimentum vitae augue quis ultricies. Nunc non mattis tellus, sed accumsan sapien. Aliquam mi neque, consequat sit amet nibh nec, tincidunt blandit est. Morbi venenatis quam eu sapien accumsan ullamcorper. Nullam sit amet elit auctor, dapibus augue id, placerat eros. Suspendisse euismod ipsum dui, a lacinia dui vestibulum maximus. Quisque volutpat, quam id laoreet pellentesque, leo orci volutpat massa, ut pretium lacus mi eget erat. Ut congue eros non augue placerat bibendum.

Sed sollicitudin turpis felis, ac efficitur nunc consequat in. In hac habitasse platea dictumst. Nullam quis condimentum risus. Praesent in mauris a ipsum tincidunt placerat. Duis eu velit mollis, scelerisque nisl non, mattis ipsum. Phasellus blandit est velit, id mattis augue vestibulum non. Nullam molestie lacus nec dignissim iaculis. Etiam molestie venenatis urna, vitae accumsan dolor tempor eget. Duis eros enim, egestas scelerisque neque quis, euismod condimentum tortor. Maecenas consectetur arcu dapibus suscipit hendrerit. In hac habitasse platea dictumst. Nulla ac magna tincidunt nibh gravida semper.

Pellentesque vestibulum sodales egestas. Donec quis pretium tortor, sed porttitor sem. Aenean rutrum arcu et malesuada egestas. Praesent eu diam est. Nullam sem ex, rhoncus vitae scelerisque at, varius at nisl. Sed at purus egestas, rhoncus tellus quis, tincidunt urna. Aliquam quis congue turpis.

Integer ut est dolor. Praesent lacinia fermentum ornare. Pellentesque malesuada suscipit massa, id ornare leo vestibulum at. Donec vestibulum sodales convallis. Nullam quis est diam. Suspendisse in tortor pulvinar, interdum enim vel, efficitur turpis. Duis tincidunt risus id diam dapibus rhoncus. Sed hendrerit magna eget ex tempor euismod. Vestibulum et ante feugiat, dignissim orci et, posuere turpis.

Etiam quis est viverra, suscipit nulla a, hendrerit lorem. Pellentesque feugiat orci id auctor gravida. Aenean finibus, neque in lobortis lobortis, nulla libero laoreet enim, non bibendum nibh urna ut est. Sed a elit felis. Integer accumsan molestie lectus eu porttitor. Sed enim enim, pretium ut velit vel, viverra vehicula erat. Aliquam erat volutpat. Suspendisse malesuada volutpat arcu a dignissim.

Etiam vulputate, lacus quis pharetra aliquet, nibh sapien laoreet arcu, eget sagittis metus mi sit amet nunc. Donec venenatis purus risus, sed placerat ante tempor id. Aenean eleifend arcu sed viverra viverra. Donec vestibulum, ante a fermentum placerat, lorem mi efficitur lectus, id viverra leo elit a ex. Vestibulum viverra ante diam, ac luctus risus sodales vitae. Phasellus non vehicula sem, sed pharetra erat. Sed nec consectetur nulla, et imperdiet dui. Nullam mi orci, elementum ut bibendum sit amet, cursus quis libero. Fusce tincidunt dictum est et vulputate. Phasellus eget ex a ante dignissim scelerisque vel eu quam. Morbi maximus ligula sed sem auctor, eget rutrum elit tempor. Etiam commodo tortor a convallis pulvinar. Integer dictum lobortis efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam convallis nunc euismod, dignissim dui faucibus, feugiat dolor.

Nullam ullamcorper magna vel imperdiet vulputate. Vivamus tincidunt, odio quis varius fringilla, elit libero laoreet arcu, nec auctor tortor odio et sapien. Duis malesuada ex non nisi dapibus suscipit. Proin consectetur bibendum dui vitae hendrerit. Interdum et malesuada fames ac ante ipsum primis in faucibus. In pellentesque molestie augue sed dapibus. Sed quis tortor egestas felis sodales viverra. Aenean fermentum pulvinar scelerisque. Morbi sollicitudin fermentum orci, at ornare justo sagittis sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum nec urna justo. Duis a egestas neque. Aliquam enim urna, dapibus vitae sodales vitae, tincidunt in eros.

Donec sit amet odio eget velit convallis rutrum lobortis sed purus. Pellentesque tincidunt congue lacus sit amet facilisis. Curabitur eget eros at libero porta pulvinar ac non neque. Suspendisse placerat ante eget tortor commodo, ut auctor tortor finibus. Etiam aliquam iaculis arcu at accumsan. Proin aliquam mollis massa in auctor. Nulla placerat interdum libero eu commodo. Nam lectus est, maximus sit amet mauris a, rhoncus mollis lorem. Phasellus dui augue, hendrerit et purus vel, rhoncus elementum dolor. Integer ac tempor orci. Nam at mi risus.""",
size=30, foreground_color=(0, 0, 0), background_color=(0, 0, 255), position=[200, 0])

    events.handle()

    display.refresh(refresh_rate=1000)