class Backspace_KEY
class Tab_KEY
class Clear_KEY
class Return_KEY
class Pause_KEY
class Escape_KEY
class Space_KEY
class ExclamationMark_KEY
class DoubleQuote_KEY
class Hashtag_KEY
class Dollar_KEY
class Ampersand_KEY
class SingleQuote_KEY
class LeftParenthesis_KEY
class RightParenthesis_KEY
class Asterisk_KEY
class Plus_KEY
class Comma_KEY
class Minus_KEY
class Period_KEY
class ForwardSlash_KEY
class Primary0_KEY
class Primary1_KEY
class Primary2_KEY
class Primary3_KEY
class Primary4_KEY
class Primary5_KEY
class Primary6_KEY
class Primary7_KEY
class Primary8_KEY
class Primary9_KEY
class Colon_KEY
class SemiColon_KEY
class LessThan_KEY
class Equals_KEY
class GreaterThan_KEY
class QuestionMark_KEY
class At_KEY
class LeftBracket_KEY
class BackSlash_KEY
class RightBracket_KEY
class Caret_KEY
class Underscore_KEY
class Grave_KEY
class PrimaryA_KEY
class PrimaryB_KEY
class PrimaryC_KEY
class PrimaryD_KEY
class PrimaryE_KEY
class PrimaryF_KEY
class PrimaryG_KEY
class PrimaryH_KEY
class PrimaryI_KEY
class PrimaryJ_KEY
class PrimaryK_KEY
class PrimaryL_KEY
class PrimaryM_KEY
class PrimaryN_KEY
class PrimaryO_KEY
class PrimaryP_KEY
class PrimaryQ_KEY
class primaryR_KEY
class PrimaryS_KEY
class PrimaryT_KEY
class PrimaryU_KEY
class PrimaryV_KEY
class PrimaryW_KEY
class PrimaryX_KEY
class PrimaryY_KEY
class PrimaryZ_KEY
class Delete_KEY
class Numpad0_KEY
class Numpad1_KEY
class Numpad2_KEY
class Numpad3_KEY
class Numpad4_KEY
class Numpad5_KEY
class Numpad6_KEY
class Numpad7_KEY
class Numpad8_KEY
class Numpad9_KEY
class NumpadPeriod_KEY
class NumpadDivide_KEY
class NumpadMultiply_KEY
class NumpadMinus_KEY
class NumpadPlus_KEY
class NumpadEnter_KEY
class NumpadEquals_KEY
class Up_KEY
class Down_KEY
class Right_KEY
class Left_KEY
class Insert_KEY
class Home_KEY
class End_KEY
class PageUp_KEY
class PageDown_KEY
class K_F1
class K_F2
class K_F3
class K_F4
class K_F5
class K_F6
class K_F7
class K_F8
class K_F9
class K_F10
class K_F11
class K_F12
class K_F13
class K_F14
class K_F15
class K_NUMLOCK
class K_CAPSLOCK
class K_SCROLLOCK
class K_RSHIFT
class K_LSHIFT
class K_RCTRL
class K_LCTRL
class K_RALT
class K_LALT
class K_RMETA
class K_LMETA
class K_LSUPER
class K_RSUPER
class K_MODE
class K_HELP
class K_PRINT
class K_SYSREQ
class K_BREAK
class K_MENU
class K_POWER
class K_EURO
class K_AC_BACK