from pmma.python_src.constants import Constants

class GPU:
    def __init__(self):
        self.accelerator_capabilities = None
        self.accounting_mode_enabled = None
        self.accounting_mode_buffer_size = None
        self.adapter_compatability = None
        self.adapter_DAC_type = None
        self.adapter_id = None
        self.adapter_index = None
        self.adapter_name = None
        self.addressing_mode = None
        self.availability = None
        self.bus_number = None
        self.capability_descriptions = None
        self.caption = None
        self.chip_to_chip_interconnect_mode = None
        self.clock_event_reasons_activity_limited = None
        self.clock_event_reasons_application_setting = None
        self.clock_event_reasons_is_hardware_limited = None
        self.clock_event_reasons_gpu_idle_limited = None
        self.clock_event_reasons_software_power_limited = None
        self.clock_event_reasons_software_thermal_limited = None
        self.clock_event_reasons_power_break_slowdown_limited = None
        self.clock_event_reasons_supported = None
        self.clock_event_reasons_sync_boost = None
        self.clock_event_reasons_thermal_limited = None
        self.color_table_entries = None
        self.compute_cap = None
        self.compute_mode = None
        self.config_manager_error_code = None
        self.config_manager_user_config = None
        self.core_voltage = None
        self.core_voltage_range = None
        self.creation_class_name = None
        self.current_bits_per_pixel = None
        self.current_horizontal_resolution = None
        self.current_number_of_colors = None
        self.current_number_of_columns = None
        self.current_number_of_rows = None
        self.current_refresh_rate = None
        self.current_scan_mode = None
        self.current_vertical_resolution = None
        self.description = None
        self.device_id = None
        self.device_specific_pens = None
        self.display_active = None
        self.display_mode = None
        self.dither_type = None
        self.driver_date = None
        self.driver_model_current = None
        self.driver_model_pending = None
        self.driver_version = None
        self.ecc_errors_corrected_all_time_in_cbu = None
        self.ecc_errors_corrected_all_time_in_primary_cache = None
        self.ecc_errors_corrected_all_time_in_register_file = None
        self.ecc_errors_corrected_all_time_in_secondary_cache = None
        self.ecc_errors_corrected_all_time_in_shared_memory = None
        self.ecc_errors_corrected_all_time_in_sram = None
        self.ecc_errors_corrected_all_time_in_texture_memory = None
        self.ecc_errors_corrected_all_time_in_total = None
        self.ecc_errors_corrected_all_time_in_video_memory = None
        self.ecc_errors_corrected_since_reboot_in_cbu = None
        self.ecc_errors_corrected_since_reboot_in_primary_cache = None
        self.ecc_errors_corrected_since_reboot_in_register_file = None
        self.ecc_errors_corrected_since_reboot_in_secondary_cache = None
        self.ecc_errors_corrected_since_reboot_in_shared_memory = None
        self.ecc_errors_corrected_since_reboot_in_sram = None
        self.ecc_errors_corrected_since_reboot_in_texture_memory = None
        self.ecc_errors_corrected_since_reboot_in_total = None
        self.ecc_errors_corrected_since_reboot_in_video_memory = None
        self.ecc_errors_uncorrected_all_time_in_cbu = None
        self.ecc_errors_uncorrected_all_time_in_primary_cache = None
        self.ecc_errors_uncorrected_all_time_in_register_file = None
        self.ecc_errors_uncorrected_all_time_in_secondary_cache = None
        self.ecc_errors_uncorrected_all_time_in_shared_memory = None
        self.ecc_errors_uncorrected_all_time_in_sram = None
        self.ecc_errors_uncorrected_all_time_in_texture_memory = None
        self.ecc_errors_uncorrected_all_time_in_total = None
        self.ecc_errors_uncorrected_all_time_in_video_memory = None
        self.ecc_errors_uncorrected_since_reboot_in_cbu = None
        self.ecc_errors_uncorrected_since_reboot_in_primary_cache = None
        self.ecc_errors_uncorrected_since_reboot_in_register_file = None
        self.ecc_errors_uncorrected_since_reboot_in_secondary_cache = None
        self.ecc_errors_uncorrected_since_reboot_in_shared_memory = None
        self.ecc_errors_uncorrected_since_reboot_in_sram = None
        self.ecc_errors_uncorrected_since_reboot_in_texture_memory = None
        self.ecc_errors_uncorrected_since_reboot_in_total = None
        self.ecc_errors_uncorrected_since_reboot_in_video_memory = None
        self.ecc_mode_current = None
        self.ecc_mode_pending = None
        self.encoder_average_FPS = None
        self.encoder_average_latency = None
        self.encoder_session_count = None
        self.engine_clock_range = None
        self.error_cleared = None
        self.error_description = None
        self.fabric_state = None
        self.fabric_status = None
        self.fan_speed_percentage = None
        self.fan_speed_percentage_range = None
        self.fan_speed_RPM = None
        self.fan_speed_RPM_range = None
        self.fractional_multi_vGPU = None
        self.frequency_application_default_shader_clock = None
        self.frequency_application_default_memory_clock = None
        self.frequency_application_memory_clock = None
        self.frequency_application_shader_clock = None
        self.frequency_maximum_memory_clock = None
        self.frequency_maximum_shader_clock = None
        self.frequency_maximum_streaming_multiprocessor_clock = None
        self.frequency_memory_clock = None
        self.frequency_shader_clock = None
        self.frequency_streaming_multiprocessor_clock = None
        self.frequency_video_clock = None
        self.heterogenous_multi_vGPU = None
        self.heterogenous_time_slice_profile = None
        self.heterogenous_time_slice_sizes = None
        self.ICM_indent = None
        self.ICM_method = None
        self.inf_filename = None
        self.inf_section = None
        self.info_ROM_ecc = None
        self.info_ROM_oem = None
        self.info_ROM_power = None
        self.info_ROM_version = None
        self.install_date = None
        self.installed_display_drivers = None
        self.last_error_code = None
        self.max_memory_supported = None
        self.max_number_controlled = None
        self.max_refresh_rate = None
        self.memory_clock_range = None
        self.memory_free = None
        self.memory_reserved = None
        self.memory_total = None
        self.memory_used = None
        self.min_refresh_rate = None
        self.monochrome = None
        self.multi_instance_GPU_mode_current = None
        self.multi_instance_GPU_mode_pending = None
        self.name = None
        self.number_of_color_planes = None
        self.number_of_video_pages = None
        self.operating_mode_current = None
        self.operating_mode_pending = None
        self.pci_bus = None
        self.pci_bus_id = None
        self.pci_device = None
        self.pci_device_id = None
        self.pci_domain = None
        self.pci_link_generation_current = None
        self.pci_link_generation_device_host_maximum = None
        self.pci_link_generation_gpu_maximum = None
        self.pci_link_generation_maximum = None
        self.pci_link_width_current = None
        self.pci_link_width_maximum = None
        self.pci_sub_device_id = None
        self.persistence_mode = None
        self.PNP_device_id = None
        self.power_draw = None
        self.power_draw_average = None
        self.power_draw_default_limit = None
        self.power_draw_enforced_limit = None
        self.power_draw_instant = None
        self.power_draw_limit = None
        self.power_draw_maximum = None
        self.power_draw_minimum = None
        self.power_management_capabilities = None
        self.power_management_supported = None
        self.protected_memory_free = None
        self.protected_memory_total = None
        self.protected_memory_used = None
        self.protocol_supported = None
        self.performance_state = None
        self.retired_pages_double_bit_ecc_errors_count = None
        self.retired_pages_single_bit_ecc_errors_count = None
        self.retired_pages_pending = None
        self.reserved_system_palette_entries = None
        self.reset_required = None
        self.reset_and_drain_recommended = None
        self.serial = None
        self.specification_version = None
        self.status = None
        self.status_info = None
        self.system_creation_class_name = None
        self.system_name = None
        self.system_palette_entries = None
        self.GPU_system_processor_mode_current = None
        self.GPU_system_processor_mode_pending = None
        self.temperature_core = None
        self.temperature_core_limit = None
        self.temperature_memory = None
        self.time_of_last_reset = None
        self.utilization_decoder = None
        self.utilization_encoder = None
        self.utilization_gpu = None
        self.utilization_jpeg = None
        self.utilization_memory = None
        self.utilization_optical_flow = None
        self.uuid = None
        self.vbios_version = None
        self.video_architecture = None
        self.video_memory_type = None
        self.video_mode = None
        self.video_mode_description = None
        self.video_processor = None


        self.operating_system_compatability__accelerator_capabilities = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__accounting_mode_enabled = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__accounting_mode_buffer_size = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__adapter_compatability = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__adapter_DAC_type = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__adapter_id = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__adapter_index = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__adapter_name = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__addressing_mode = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__availability = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__bus_number = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__capability_descriptions = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__caption = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__chip_to_chip_interconnect_mode = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_activity_limited = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_application_setting = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_is_hardware_limited = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_gpu_idle_limited = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_software_power_limited = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_software_thermal_limited = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_power_break_slowdown_limited = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_supported = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_sync_boost = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__clock_event_reasons_thermal_limited = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__color_table_entries = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__compute_cap = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__compute_mode = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__config_manager_error_code = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__config_manager_user_config = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__core_voltage = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__core_voltage_range = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__creation_class_name = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__current_bits_per_pixel = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__current_horizontal_resolution = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__current_number_of_colors = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__current_number_of_columns = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__current_number_of_rows = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__current_refresh_rate = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__current_scan_mode = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__current_vertical_resolution = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__description = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__device_id = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__device_specific_pens = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__display_active = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__display_mode = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__dither_type = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__driver_date = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__driver_model_current = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__driver_model_pending = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__driver_version = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_cbu = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_primary_cache = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_register_file = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_secondary_cache = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_shared_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_sram = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_texture_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_total = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_all_time_in_video_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_cbu = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_primary_cache = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_register_file = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_secondary_cache = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_shared_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_sram = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_texture_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_total = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_corrected_since_reboot_in_video_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_cbu = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_primary_cache = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_register_file = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_secondary_cache = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_shared_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_sram = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_texture_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_total = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_all_time_in_video_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_cbu = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_primary_cache = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_register_file = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_secondary_cache = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_shared_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_sram = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_texture_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_total = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_errors_uncorrected_since_reboot_in_video_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_mode_current = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ecc_mode_pending = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__encoder_average_FPS = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__encoder_average_latency = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__encoder_session_count = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__engine_clock_range = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__error_cleared = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__error_description = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__fabric_state = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__fabric_status = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__fan_speed_percentage = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__fan_speed_percentage_range = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__fan_speed_RPM = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__fan_speed_RPM_range = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__fractional_multi_vGPU = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_application_default_shader_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_application_default_memory_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_application_memory_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_application_shader_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_maximum_memory_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_maximum_shader_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_maximum_streaming_multiprocessor_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_memory_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_shader_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_streaming_multiprocessor_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__frequency_video_clock = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__heterogenous_multi_vGPU = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__heterogenous_time_slice_profile = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__heterogenous_time_slice_sizes = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ICM_indent = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__ICM_method = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__inf_filename = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__inf_section = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__info_ROM_ecc = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__info_ROM_oem = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__info_ROM_power = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__info_ROM_version = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__install_date = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__installed_display_drivers = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__last_error_code = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__max_memory_supported = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__max_number_controlled = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__max_refresh_rate = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__memory_clock_range = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__memory_free = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__memory_reserved = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__memory_total = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__memory_used = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__min_refresh_rate = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__monochrome = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__multi_instance_GPU_mode_current = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__multi_instance_GPU_mode_pending = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__name = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__number_of_color_planes = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__number_of_video_pages = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__operating_mode_current = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__operating_mode_pending = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_bus = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_bus_id = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_device = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_device_id = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_domain = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_link_generation_current = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_link_generation_device_host_maximum = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_link_generation_gpu_maximum = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_link_generation_maximum = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_link_width_current = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_link_width_maximum = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__pci_sub_device_id = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__persistence_mode = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__PNP_device_id = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_draw = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_draw_average = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_draw_default_limit = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_draw_enforced_limit = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_draw_instant = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_draw_limit = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_draw_maximum = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_draw_minimum = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_management_capabilities = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__power_management_supported = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__protected_memory_free = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__protected_memory_total = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__protected_memory_used = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__protocol_supported = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__performance_state = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__retired_pages_double_bit_ecc_errors_count = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__retired_pages_single_bit_ecc_errors_count = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__retired_pages_pending = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__reserved_system_palette_entries = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__reset_required = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__reset_and_drain_recommended = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__serial = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__specification_version = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__status = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__status_info = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__system_creation_class_name = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__system_name = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__system_palette_entries = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__GPU_system_processor_mode_current = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__GPU_system_processor_mode_pending = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__temperature_core = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__temperature_core_limit = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__temperature_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__time_of_last_reset = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__utilization_decoder = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__utilization_encoder = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__utilization_gpu = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__utilization_jpeg = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__utilization_memory = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__utilization_optical_flow = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__uuid = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__vbios_version = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__video_architecture = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__video_memory_type = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__video_mode = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__video_mode_description = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}
        self.operating_system_compatability__video_processor = {Constants.WINDOWS: None, Constants.LINUX: None, Constants.MACOS: None, Constants.JAVA: None}


        self.internal_name__accelerator_capabilities = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__accounting_mode_enabled = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__accounting_mode_buffer_size = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__adapter_compatability = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__adapter_DAC_type = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__adapter_id = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__adapter_index = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__adapter_name = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__addressing_mode = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__availability = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__bus_number = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__capability_descriptions = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__caption = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__chip_to_chip_interconnect_mode = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_activity_limited = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_application_setting = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_is_hardware_limited = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_gpu_idle_limited = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_software_power_limited = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_software_thermal_limited = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_power_break_slowdown_limited = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_supported = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_sync_boost = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__clock_event_reasons_thermal_limited = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__color_table_entries = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__compute_cap = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__compute_mode = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__config_manager_error_code = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__config_manager_user_config = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__core_voltage = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__core_voltage_range = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__creation_class_name = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__current_bits_per_pixel = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__current_horizontal_resolution = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__current_number_of_colors = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__current_number_of_columns = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__current_number_of_rows = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__current_refresh_rate = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__current_scan_mode = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__current_vertical_resolution = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__description = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__device_id = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__device_specific_pens = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__display_active = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__display_mode = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__dither_type = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__driver_date = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__driver_model_current = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__driver_model_pending = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__driver_version = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_cbu = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_primary_cache = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_register_file = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_secondary_cache = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_shared_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_sram = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_texture_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_total = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_all_time_in_video_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_cbu = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_primary_cache = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_register_file = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_secondary_cache = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_shared_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_sram = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_texture_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_total = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_corrected_since_reboot_in_video_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_cbu = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_primary_cache = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_register_file = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_secondary_cache = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_shared_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_sram = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_texture_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_total = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_all_time_in_video_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_cbu = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_primary_cache = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_register_file = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_secondary_cache = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_shared_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_sram = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_texture_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_total = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_errors_uncorrected_since_reboot_in_video_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_mode_current = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ecc_mode_pending = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__encoder_average_FPS = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__encoder_average_latency = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__encoder_session_count = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__engine_clock_range = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__error_cleared = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__error_description = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__fabric_state = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__fabric_status = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__fan_speed_percentage = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__fan_speed_percentage_range = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__fan_speed_RPM = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__fan_speed_RPM_range = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__fractional_multi_vGPU = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_application_default_shader_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_application_default_memory_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_application_memory_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_application_shader_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_maximum_memory_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_maximum_shader_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_maximum_streaming_multiprocessor_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_memory_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_shader_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_streaming_multiprocessor_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__frequency_video_clock = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__heterogenous_multi_vGPU = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__heterogenous_time_slice_profile = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__heterogenous_time_slice_sizes = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ICM_indent = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__ICM_method = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__inf_filename = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__inf_section = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__info_ROM_ecc = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__info_ROM_oem = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__info_ROM_power = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__info_ROM_version = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__install_date = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__installed_display_drivers = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__last_error_code = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__max_memory_supported = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__max_number_controlled = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__max_refresh_rate = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__memory_clock_range = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__memory_free = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__memory_reserved = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__memory_total = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__memory_used = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__min_refresh_rate = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__monochrome = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__multi_instance_GPU_mode_current = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__multi_instance_GPU_mode_pending = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__name = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__number_of_color_planes = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__number_of_video_pages = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__operating_mode_current = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__operating_mode_pending = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_bus = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_bus_id = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_device = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_device_id = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_domain = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_link_generation_current = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_link_generation_device_host_maximum = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_link_generation_gpu_maximum = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_link_generation_maximum = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_link_width_current = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_link_width_maximum = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__pci_sub_device_id = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__persistence_mode = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__PNP_device_id = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_draw = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_draw_average = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_draw_default_limit = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_draw_enforced_limit = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_draw_instant = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_draw_limit = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_draw_maximum = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_draw_minimum = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_management_capabilities = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__power_management_supported = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__protected_memory_free = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__protected_memory_total = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__protected_memory_used = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__protocol_supported = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__performance_state = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__retired_pages_double_bit_ecc_errors_count = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__retired_pages_single_bit_ecc_errors_count = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__retired_pages_pending = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__reserved_system_palette_entries = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__reset_required = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__reset_and_drain_recommended = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__serial = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__specification_version = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__status = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__status_info = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__system_creation_class_name = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__system_name = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__system_palette_entries = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__GPU_system_processor_mode_current = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__GPU_system_processor_mode_pending = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__temperature_core = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__temperature_core_limit = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__temperature_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__time_of_last_reset = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__utilization_decoder = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__utilization_encoder = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__utilization_gpu = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__utilization_jpeg = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__utilization_memory = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__utilization_optical_flow = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__uuid = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__vbios_version = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__video_architecture = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__video_memory_type = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__video_mode = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__video_mode_description = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}
        self.internal_name__video_processor = {Constants.SMI: [], Constants.WMI: [], Constants.PYADL: []}