version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: documentation/docs/requirements.txt

sphinx:
  configuration: documentation/docs/conf.py

formats: all
