name: Test pmma in manylinux2014

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-manylinux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dummy repo (if needed)
      uses: actions/checkout@v4

    - name: Set up Docker container (manylinux2014)
      run: |
        docker run --rm -v $(pwd):/io quay.io/pypa/manylinux2014_x86_64 /bin/bash -c "
          # Install Python and pip
          yum install -y python3 python3-pip

          # Install pmma
          python3 -m pip install --upgrade pip
          python3 -m pip install pmma==5.0.0

          # Run a basic check
          python3 -c 'import pmma; print(pmma.__version__)'
        "
