name: Deploy to Distributable Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create pmma directory and copy files
        run: |
          mkdir -p pmma
          cp -r python_src pmma/
          cp -r cython_src pmma/
          cp -r shaders pmma/
          cp README.md pmma/
          cp requirements.txt pmma/
          cp setup.py pmma/
          cp __init__.py pmma/
          cp pyproject.toml pmma/

      - name: Check out distributable branch
        run: |
          git fetch origin distributable || true
          git checkout -B distributable origin/distributable || git checkout -b distributable

      - name: Sync pmma directory with distributable branch
        run: |
          rm -rf pmma
          mv pmma pmma
          git add pmma

      - name: Commit and push changes if there are any
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          if ! git diff-index --quiet HEAD; then
            git commit -m "Deploy to distributable branch"
            git push origin distributable --force
          else
            echo "No changes to commit"
          fi
