name: Update Distributables Branch

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  update_distributables:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches and history

      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Delete all contents in distributables branch
        run: |
          git checkout distributables || git checkout -b distributables
          git rm -rf . # Remove all files in distributables branch

      - name: Create pmma directory in distributables branch
        run: mkdir -p pmma

      - name: Copy contents from main branch
        run: |
          git checkout main -- cython_src python_src shaders
          cp -r cython_src pmma/
          cp -r python_src pmma/
          cp -r shaders pmma/

      - name: Delete original files in distributables branch
        run: |
            rm -rf cython_src
            rm -rf python_src
            rm -rf shaders

      - name: Commit and push changes to distributables branch
        run: |
          git add pmma
          git commit -m "Update distributables branch with latest pmma content"
          git push origin distributables --force
