name: Windows CMAKE test

on:
  workflow_dispatch:

jobs:
  build_deps_windows:
    name: Build Windows Dependencies
    runs-on: windows-latest
    steps:
      - name: Check CMake version
        run: cmake --version